#!/bin/sh
java "-Dcom.sun.management.jmxremote" \
"-Dcom.sun.management.jmxremote.port=9010" \
"-Dcom.sun.management.jmxremote.rmi.port=9011" \
"-Dcom.sun.management.jmxremote.local.only=false" \
"-Dcom.sun.management.jmxremote.authenticate=false" \
"-Dcom.sun.management.jmxremote.ssl=false" \
-Djava.rmi.server.hostname=$(cat external_host_ip) \
-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n \
-XX:+HeapDumpOnOutOfMemoryError \
-jar dag.jar

