# docker-compose.yml
version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention=200h
    volumes:
      - ./grafana-dashboard/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - '9100:9100'
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-dashboard/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
  constellation:
    image: constellationlabs/constellation:latest
    depends_on:
      - grafana
    ports:
      - "2551:2551"
      - "6006:6006"
      - "9000:9000"
      - "9001:9001"
      - "9010:9010"