{
 "title": "Alerting",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Instance" }
  ]
 },
 "panels": [
  { "title": "Health", "type": "alertlist", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 } },
  { "title": "Join & Leave", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Join height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "dag_cluster_ownJoinedHeight", "legendFormat": "{{ alias }}" }
   ]
  },
  {
   "title": "Average snapshot count per minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(dag_snapshotCount_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dag_cluster_ownJoinedHeight)"
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_checkpoints_total", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Accepted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_checkpoints_accepted", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Waiting for resolving",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_checkpoints_waitingForResolving",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "In snapshot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_checkpoints_inSnapshot", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Waiting for acceptance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_checkpoints_waitingForAcceptance",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Waiting for acceptance after download",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_checkpoints_waitingForAcceptanceAfterDownload",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Active tips",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_activeTips", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Checkpoints - min tip height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_minTipHeight", "legendFormat": "{{ instance }}" }
   ]
  },
  { "title": "Snapshots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Created count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "dag_snapshotCount_total", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Creation failures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_snapshotAttempt_failure_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Created snapshots",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_createdSnapshots",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Next height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "dag_nextSnapshotHeight", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Accepted snapshots",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_acceptedSnapshots",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last snapshot height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "dag_lastSnapshotHeight", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Latest majority height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_lastestMajorityHeight",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Lowest majority height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_lowestMajorityHeight",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Max majority state height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(dag_redownload_lastestMajorityHeight)",
     "legendFormat": "Max height"
    }
   ]
  },
  {
   "title": "Height below",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "dag_heightBelow_total", "legendFormat": "{{ instance }}" }
   ]
  },
  { "title": "Download / Redownload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Redownload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_reDownloadFinished_total", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "dag_downloadFinished_total", "legendFormat": "{{ alias }}" }
   ]
  },
  {
   "title": "Last redownload fail",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_hasLastRedownloadFailed",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "Redownload failures - total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_redownloadFailures_total",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  { "title": "Gossip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Started gossip rounds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_gossip_spreadInitCount_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Finished gossip rounds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_gossip_succeededSpreadInitCount_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Bisects due to a timeout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_gossip_failedSpreadInitCount_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Bisects due to an error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_gossip_errorSpreadInitCount_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Forward error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_gossip_errorSpreadForwardCount_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Healthcheck", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "InProgress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_inProgressRoundsCount",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Historical",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_historicalRoundsCount",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "KeepUp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_keepUpRoundsCount",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Reconciliation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_ownReconciliationRounds_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Decision - PeerOnline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_decision_PeerOnline_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Decision - PeerOffline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_decision_PeerOffline_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Historical - Own",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_historicalOwnRoundsCount",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Historical - Peer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_historicalPeerRoundsCount",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Historical - KeepUp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_historicalKeepUpRoundsCount",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Healthcheck - peer removal from consensus reason",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 }
  },
  {
   "title": "LeftDuringConsensus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_peerRemovedFromConsensus_LeftDuringConsensus_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "LostReferenceThroughProxy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_peerRemovedFromConsensus_LostReferenceThroughProxy_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "PeerCouldNotProvideProposal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_peerRemovedFromConsensus_PeerCouldNotProvideProposal_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "UnresponsiveWithParallelRound",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_peerRemovedFromConsensus_UnresponsiveWithParallelRound_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "ParallelRoundDecidedPeerIsOffline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_peerRemovedFromConsensus_ParallelRoundDecidedPeerIsOffline_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Healthcheck - warnings/erros", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 } },
  {
   "title": "Fatal integrity errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_fatalIntegrityErrorOccurred_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Attempted to process Historical Round",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_attemptedToProcessHistoricalRoundProposal_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Suspicious warning occurred",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_healthcheck_suspiciousWarningOccurred_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Transactions / Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 182 } },
  {
   "title": "Double spend incidents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_doubleSpendTransactions" }
   ]
  },
  {
   "title": "Missing parents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 183 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "dag_missingParents_total", "legendFormat": "{{ alias }}" }
   ]
  },
  {
   "title": "Buffer size for redownloads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 191 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_syncBufferSize", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Transactions - max (w/o genesis)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 191 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(dag_transactionService_pending_notDummy_size)",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(dag_transactionService_inConsensus_notDummy_size)",
     "legendFormat": "In consensus"
    },
    {
     "expr": "max(dag_transactionService_accepted_notDummy_size) - 292",
     "legendFormat": "Accepted"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 199 } },
  {
   "title": "Started own consensus rounds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_startOwnRound_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Participated in consensus rounds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 200 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_participateInRound_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Participated consensus rounds - invalid node state error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 200 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_participateInRound_invalidNodeStateError_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Own consensus rounds - consensus error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_startOwnRound_consensusError_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Own consensus rounds - another round already in progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 208 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_startOwnRound_consensusStartError_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Own consensus rounds - no peers for consensus error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 208 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_startOwnRound_noPeersForConsensusError_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Own consensus rounds - no tips for consensus error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 216 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_startOwnRound_noTipsForConsensusError_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Active tips",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 216 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "dag_activeTips", "legendFormat": "{{alias}}" }
   ]
  },
  { "title": "Cloud storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 224 } },
  {
   "title": "Data migration failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 225 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_sendToCloud_failure_total", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 231 } },
  {
   "title": "CPU (process)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 232 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{ alias }}" }
   ]
  },
  {
   "title": "JVM Used Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 232 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"heap\"}) by (alias)/sum(jvm_memory_max_bytes{area=\"heap\"}) by (alias))*100",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "CPU (system)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 240 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "{{ alias }}" }
   ]
  },
  {
   "title": "JVM Committed Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 240 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(jvm_memory_committed_bytes{area=\"heap\"}) by (alias)/sum(jvm_memory_max_bytes{area=\"heap\"}) by (alias))*100",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "Disk space (used)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 248 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(disk_total_bytes - disk_free_bytes) / disk_total_bytes",
     "legendFormat": "{{ alias }}"
    }
   ]
  }
 ]
}