{
 "title": "Http4s",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "[Client] Active requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active GET requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "org_http4s_client_active_request_count{classifier=\"get\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active POST requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "org_http4s_client_active_request_count{classifier=\"post\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[Client] Response duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "GET (headers phase)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "org_http4s_client_response_duration_seconds_count{phase=\"headers\", method=\"get\"}/org_http4s_client_response_duration_seconds_sum{phase=\"headers\", method=\"get\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GET (body phase)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "org_http4s_client_response_duration_seconds_count{phase=\"body\", method=\"get\"}/org_http4s_client_response_duration_seconds_sum{phase=\"body\", method=\"get\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "POST (headers phase)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "org_http4s_client_response_duration_seconds_count{phase=\"headers\", method=\"post\"}/org_http4s_client_response_duration_seconds_sum{phase=\"headers\", method=\"post\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "POST (body phase)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "org_http4s_client_response_duration_seconds_count{phase=\"body\", method=\"post\"}/org_http4s_client_response_duration_seconds_sum{phase=\"body\", method=\"post\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "[Server] Request count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Active",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_http4s_server_active_request_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GET 2xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_http4s_server_request_count{method=\"get\", status=\"2xx\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GET 4xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_http4s_server_request_count{method=\"get\", status=\"4xx\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GET 5xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_http4s_server_request_count{method=\"get\", status=\"5xx\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "POST 2xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_http4s_server_request_count{method=\"post\", status=\"2xx\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "POST 4xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_http4s_server_request_count{method=\"post\", status=\"4xx\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "POST 5xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_http4s_server_request_count{method=\"post\", status=\"5xx\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[Server] Response duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "GET (headers phase)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "org_http4s_server_response_duration_seconds_count{phase=\"headers\", method=\"get\"}/org_http4s_server_response_duration_seconds_sum{phase=\"headers\", method=\"get\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GET (body phase)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "org_http4s_server_response_duration_seconds_count{phase=\"body\", method=\"get\"}/org_http4s_server_response_duration_seconds_sum{phase=\"body\", method=\"get\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "POST (headers phase)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "org_http4s_server_response_duration_seconds_count{phase=\"headers\", method=\"post\"}/org_http4s_server_response_duration_seconds_sum{phase=\"headers\", method=\"post\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "POST (body phase)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "org_http4s_server_response_duration_seconds_count{phase=\"body\", method=\"post\"}/org_http4s_server_response_duration_seconds_sum{phase=\"body\", method=\"post\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}