apiVersion: v1
kind: Service
metadata:
  name: constellation-node-rpc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: akka-http
  selector:
    app: constellation
  type: NodePort