apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: constellation-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: constellation
    spec:
      containers:
      - name: constellation-node
        image: constellation/constellation:latest
        imagePullPolicy: Never # Only use the local image
        ports:
        - containerPort: 9000  # The kubectl proxy will default to the first port in the list
          name: akka-http
          protocol: TCP
        - containerPort: 2551
          name: akka-remote
          protocol: TCP
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: AKKA_ACTOR_SYSTEM_NAME
          value: constellation
        - name: AKKA_ACTOR_SYSTEM_NAME
          value: sharding-sample
        - name: AKKA_REMOTING_BIND_HOST
          value: "$(POD_IP)"
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_SEED_NODE_PORT
          value: '2551'
        - name: SAMPLE_HTTP_PORT
          value: '8080'
        - name: SAMPLE_HTTP_HOST
          value: "$(POD_IP)"
        readinessProbe:
          tcpSocket:
            port: 2551
          initialDelaySeconds: 30
          timeoutSeconds: 30