{
 "title": "Alerting",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Health", "type": "alertlist", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Join & Leave",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Join height",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "dag_cluster_ownJoinedHeight", "legendFormat": "{{ instance }}" }
     ]
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Created count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "dag_snapshotCount_total", "legendFormat": "{{ instance }}" }
     ]
    },
    {
     "title": "Created height",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dag_redownload_maxCreatedSnapshotHeight",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Creation failures",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dag_snapshotAttempt_failure_total",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Majority state height",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dag_redownload_lastMajorityStateHeight",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Accepted height",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dag_redownload_maxAcceptedSnapshotHeight",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Next height",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "dag_nextSnapshotHeight", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "Download / Redownload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redownload",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "dag_reDownloadFinished_total", "legendFormat": "{{ instance }}" }
     ]
    },
    {
     "title": "Download",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "dag_downloadFinished_total", "legendFormat": "{{ instance }}" }
     ]
    }
   ]
  },
  {
   "title": "Transactions / Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Double spend incidents",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "dag_doubleSpendTransactions" }
     ]
    },
    {
     "title": "Missing parents",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "dag_missingParents", "legendFormat": "{{ instance }}" }
     ]
    }
   ]
  },
  {
   "title": "Cloud storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cloud height",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(dag_redownload_lastSentHeight) > -1",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Data migration failures",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "dag_sendToCloud_failure", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true
  },
  {
   "title": "JVM Committed Heap",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(jvm_memory_committed_bytes{area=\"heap\"}) by (instance)/sum(jvm_memory_max_bytes{area=\"heap\"}) by (instance))*100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "JVM Used Heap",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"heap\"}) by (instance)/sum(jvm_memory_max_bytes{area=\"heap\"}) by (instance))*100",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}