{
 "title": "Alerting",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Health", "type": "alertlist", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 } },
  { "title": "Join & Leave", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Join height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "dag_cluster_ownJoinedHeight", "legendFormat": "{{ alias }}" }
   ]
  },
  { "title": "Snapshots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Created count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_snapshotCount_total", "legendFormat": "{{ alias }}" }
   ]
  },
  {
   "title": "Created height",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_maxCreatedSnapshotHeight",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Next height",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_nextSnapshotHeight", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Majority state height",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_lastMajorityStateHeight",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Accepted height",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_maxAcceptedSnapshotHeight",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Max majority state height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(dag_redownload_lastMajorityStateHeight)",
     "legendFormat": "Max height"
    }
   ]
  },
  { "title": "Download / Redownload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Redownload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_reDownloadFinished_total", "legendFormat": "{{ alias }}" }
   ]
  },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_downloadFinished_total", "legendFormat": "{{ alias }}" }
   ]
  },
  { "title": "Transactions / Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Double spend incidents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_doubleSpendTransactions" }
   ]
  },
  { "title": "Cloud storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Cloud height",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_lastSentHeight > -1",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}