{
 "title": "Alerting",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Health", "type": "alertlist", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 } },
  { "title": "Join & Leave", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Join height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "dag_cluster_ownJoinedHeight", "legendFormat": "{{ alias }}" }
   ]
  },
  {
   "title": "Average snapshot creation time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "increase(dag_snapshotCount_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Snapshots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Created count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_snapshotCount_total", "legendFormat": "{{ alias }}" }
   ]
  },
  {
   "title": "Created height",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_maxCreatedSnapshotHeight",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Creation failures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_snapshotAttempt_failure_total",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "Majority state height",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_lastMajorityStateHeight",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Accepted height",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_maxAcceptedSnapshotHeight",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Next height",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_nextSnapshotHeight", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Max majority state height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(dag_redownload_lastMajorityStateHeight)",
     "legendFormat": "Max height"
    }
   ]
  },
  { "title": "Download / Redownload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Redownload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_reDownloadFinished_total", "legendFormat": "{{ alias }}" }
   ]
  },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_downloadFinished_total", "legendFormat": "{{ alias }}" }
   ]
  },
  { "title": "Transactions / Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Double spend incidents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_doubleSpendTransactions" }
   ]
  },
  {
   "title": "Missing parents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_missingParents_total", "legendFormat": "{{ alias }}" }
   ]
  },
  {
   "title": "Buffer size for redownloads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_syncBufferSize", "legendFormat": "{{alias}}" }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Started own consensus rounds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_startOwnRound_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Participated in consensus rounds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_participateInRound_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Participated consensus rounds - invalid node state error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_participateInRound_invalidNodeStateError_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Own consensus rounds - consensus error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_startOwnRound_consensusError_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Own consensus rounds - another round already in progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_startOwnRound_consensusStartError_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Own consensus rounds - no peers for consensus error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_startOwnRound_noPeersForConsensusError_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Own consensus rounds - no tips for consensus error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_consensus_startOwnRound_noTipsForConsensusError_total",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Active tips",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_activeTips", "legendFormat": "{{alias}}" }
   ]
  },
  { "title": "Cloud storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Cloud height",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dag_redownload_lastSentHeight > -1",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Data migration failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dag_sendToCloud_failure_total", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "CPU (process)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{ alias }}" }
   ]
  },
  {
   "title": "JVM Used Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"heap\"}) by (alias)/sum(jvm_memory_max_bytes{area=\"heap\"}) by (alias))*100",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "CPU (system)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "{{ alias }}" }
   ]
  },
  {
   "title": "JVM Committed Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(jvm_memory_committed_bytes{area=\"heap\"}) by (alias)/sum(jvm_memory_max_bytes{area=\"heap\"}) by (alias))*100",
     "legendFormat": "{{ alias }}"
    }
   ]
  }
 ]
}