on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: little-core-labs/get-git-tag@v3.0.1 # https://github.com/olegtarasov/get-tag/issues/14
        id: tagName
        with:
          tagRegex: "v(.*)"
          tagRegexGroup: 1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Assemble assets
        run: |
          sbt "++ 2.12.10" "keytool/assembly" "++ 2.12.10" "wallet/assembly" "++ 2.12.10" "schema/assembly"
          mkdir -p ./src/main/resources/ui/
          cd ui && sbt clean fullOptJS && cd ..
          cp ./ui/target/scala-2.12/*js* ./src/main/resources/ui/
          sbt "++ 2.12.10" assembly

      - name: Copy dependencies
        run: |
          cp ./keytool/target/scala-2.12/keytool-assembly-${{ steps.tagName.outputs.tag }}.jar docker/keytool/cl-keytool.jar
          cp ./wallet/target/scala-2.12/wallet-assembly-${{ steps.tagName.outputs.tag }}.jar docker/wallet/cl-wallet.jar
          cp ./schema/target/scala-2.12/schema-assembly-${{ steps.tagName.outputs.tag }}.jar docker/schema/cl-schema.jar
          cp ./target/scala-2.12/constellation-assembly-${{ steps.tagName.outputs.tag }}.jar docker/node/cl-node.jar

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.tagName.outputs.tag }}
          draft: true
          prerelease: false
          body_path: CHANGELOG.md
          files: |
            docker/keytool/cl-keytool.jar
            docker/wallet/cl-wallet.jar
            docker/schema/cl-schema.jar
            docker/node/cl-node.jar
            main-net/mainnet-whitelisting
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish docker keytool image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: constellationprotocol/keytool
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker/keytool
          tag_semver: true

      - name: Publish docker wallet image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: constellationprotocol/wallet
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker/wallet
          tag_semver: true

      - name: Publish docker node image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: constellationprotocol/node
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker/node
          tag_semver: true